/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CvRouteImport } from './routes/cv'
import { Route as HowIWorkRouteImport } from './routes/how-i-work'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as ArenaActivityHeatmapRouteImport } from './routes/arena/activity-heatmap'
import { Route as ArenaCanvasCrowdRouteImport } from './routes/arena/canvas-crowd'
import { Route as ArenaDesignArenaRouteImport } from './routes/arena/design-arena'
import { Route as ArenaPeriodicTableRouteImport } from './routes/arena/periodic-table'
import { Route as WritingIndexRouteImport } from './routes/writing.index'
import { Route as WritingSlugRouteImport } from './routes/writing.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CvRoute = CvRouteImport.update({
  id: '/cv',
  path: '/cv',
  getParentRoute: () => rootRouteImport,
} as any)
const HowIWorkRoute = HowIWorkRouteImport.update({
  id: '/how-i-work',
  path: '/how-i-work',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ArenaActivityHeatmapRoute = ArenaActivityHeatmapRouteImport.update({
  id: '/arena/activity-heatmap',
  path: '/arena/activity-heatmap',
  getParentRoute: () => rootRouteImport,
} as any)
const ArenaCanvasCrowdRoute = ArenaCanvasCrowdRouteImport.update({
  id: '/arena/canvas-crowd',
  path: '/arena/canvas-crowd',
  getParentRoute: () => rootRouteImport,
} as any)
const ArenaDesignArenaRoute = ArenaDesignArenaRouteImport.update({
  id: '/arena/design-arena',
  path: '/arena/design-arena',
  getParentRoute: () => rootRouteImport,
} as any)
const ArenaPeriodicTableRoute = ArenaPeriodicTableRouteImport.update({
  id: '/arena/periodic-table',
  path: '/arena/periodic-table',
  getParentRoute: () => rootRouteImport,
} as any)
const WritingIndexRoute = WritingIndexRouteImport.update({
  id: '/writing/',
  path: '/writing/',
  getParentRoute: () => rootRouteImport,
} as any)
const WritingSlugRoute = WritingSlugRouteImport.update({
  id: '/writing/$slug',
  path: '/writing/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cv': typeof CvRoute
  '/how-i-work': typeof HowIWorkRoute
  '/projects': typeof ProjectsRoute
  '/arena/activity-heatmap': typeof ArenaActivityHeatmapRoute
  '/arena/canvas-crowd': typeof ArenaCanvasCrowdRoute
  '/arena/design-arena': typeof ArenaDesignArenaRoute
  '/arena/periodic-table': typeof ArenaPeriodicTableRoute
  '/writing/$slug': typeof WritingSlugRoute
  '/writing/': typeof WritingIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cv': typeof CvRoute
  '/how-i-work': typeof HowIWorkRoute
  '/projects': typeof ProjectsRoute
  '/arena/activity-heatmap': typeof ArenaActivityHeatmapRoute
  '/arena/canvas-crowd': typeof ArenaCanvasCrowdRoute
  '/arena/design-arena': typeof ArenaDesignArenaRoute
  '/arena/periodic-table': typeof ArenaPeriodicTableRoute
  '/writing/$slug': typeof WritingSlugRoute
  '/writing': typeof WritingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cv': typeof CvRoute
  '/how-i-work': typeof HowIWorkRoute
  '/projects': typeof ProjectsRoute
  '/arena/activity-heatmap': typeof ArenaActivityHeatmapRoute
  '/arena/canvas-crowd': typeof ArenaCanvasCrowdRoute
  '/arena/design-arena': typeof ArenaDesignArenaRoute
  '/arena/periodic-table': typeof ArenaPeriodicTableRoute
  '/writing/$slug': typeof WritingSlugRoute
  '/writing/': typeof WritingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/cv'
    | '/how-i-work'
    | '/projects'
    | '/arena/activity-heatmap'
    | '/arena/canvas-crowd'
    | '/arena/design-arena'
    | '/arena/periodic-table'
    | '/writing/$slug'
    | '/writing/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/cv'
    | '/how-i-work'
    | '/projects'
    | '/arena/activity-heatmap'
    | '/arena/canvas-crowd'
    | '/arena/design-arena'
    | '/arena/periodic-table'
    | '/writing/$slug'
    | '/writing'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/cv'
    | '/how-i-work'
    | '/projects'
    | '/arena/activity-heatmap'
    | '/arena/canvas-crowd'
    | '/arena/design-arena'
    | '/arena/periodic-table'
    | '/writing/$slug'
    | '/writing/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CvRoute: typeof CvRoute
  HowIWorkRoute: typeof HowIWorkRoute
  ProjectsRoute: typeof ProjectsRoute
  ArenaActivityHeatmapRoute: typeof ArenaActivityHeatmapRoute
  ArenaCanvasCrowdRoute: typeof ArenaCanvasCrowdRoute
  ArenaDesignArenaRoute: typeof ArenaDesignArenaRoute
  ArenaPeriodicTableRoute: typeof ArenaPeriodicTableRoute
  WritingSlugRoute: typeof WritingSlugRoute
  WritingIndexRoute: typeof WritingIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cv': {
      id: '/cv'
      path: '/cv'
      fullPath: '/cv'
      preLoaderRoute: typeof CvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-i-work': {
      id: '/how-i-work'
      path: '/how-i-work'
      fullPath: '/how-i-work'
      preLoaderRoute: typeof HowIWorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arena/activity-heatmap': {
      id: '/arena/activity-heatmap'
      path: '/arena/activity-heatmap'
      fullPath: '/arena/activity-heatmap'
      preLoaderRoute: typeof ArenaActivityHeatmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arena/canvas-crowd': {
      id: '/arena/canvas-crowd'
      path: '/arena/canvas-crowd'
      fullPath: '/arena/canvas-crowd'
      preLoaderRoute: typeof ArenaCanvasCrowdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arena/design-arena': {
      id: '/arena/design-arena'
      path: '/arena/design-arena'
      fullPath: '/arena/design-arena'
      preLoaderRoute: typeof ArenaDesignArenaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arena/periodic-table': {
      id: '/arena/periodic-table'
      path: '/arena/periodic-table'
      fullPath: '/arena/periodic-table'
      preLoaderRoute: typeof ArenaPeriodicTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/writing/': {
      id: '/writing/'
      path: '/writing'
      fullPath: '/writing/'
      preLoaderRoute: typeof WritingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/writing/$slug': {
      id: '/writing/$slug'
      path: '/writing/$slug'
      fullPath: '/writing/$slug'
      preLoaderRoute: typeof WritingSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CvRoute: CvRoute,
  HowIWorkRoute: HowIWorkRoute,
  ProjectsRoute: ProjectsRoute,
  ArenaActivityHeatmapRoute: ArenaActivityHeatmapRoute,
  ArenaCanvasCrowdRoute: ArenaCanvasCrowdRoute,
  ArenaDesignArenaRoute: ArenaDesignArenaRoute,
  ArenaPeriodicTableRoute: ArenaPeriodicTableRoute,
  WritingSlugRoute: WritingSlugRoute,
  WritingIndexRoute: WritingIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
