/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ArenaActivityHeatmapRouteImport } from './routes/arena/activity-heatmap'
import { Route as ArenaCanvasCrowdRouteImport } from './routes/arena/canvas-crowd'
import { Route as ArenaDesignArenaRouteImport } from './routes/arena/design-arena'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ArenaActivityHeatmapRoute = ArenaActivityHeatmapRouteImport.update({
  id: '/arena/activity-heatmap',
  path: '/arena/activity-heatmap',
  getParentRoute: () => rootRouteImport,
} as any)
const ArenaCanvasCrowdRoute = ArenaCanvasCrowdRouteImport.update({
  id: '/arena/canvas-crowd',
  path: '/arena/canvas-crowd',
  getParentRoute: () => rootRouteImport,
} as any)
const ArenaDesignArenaRoute = ArenaDesignArenaRouteImport.update({
  id: '/arena/design-arena',
  path: '/arena/design-arena',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/arena/activity-heatmap': typeof ArenaActivityHeatmapRoute
  '/arena/canvas-crowd': typeof ArenaCanvasCrowdRoute
  '/arena/design-arena': typeof ArenaDesignArenaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/arena/activity-heatmap': typeof ArenaActivityHeatmapRoute
  '/arena/canvas-crowd': typeof ArenaCanvasCrowdRoute
  '/arena/design-arena': typeof ArenaDesignArenaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/arena/activity-heatmap': typeof ArenaActivityHeatmapRoute
  '/arena/canvas-crowd': typeof ArenaCanvasCrowdRoute
  '/arena/design-arena': typeof ArenaDesignArenaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/arena/activity-heatmap'
    | '/arena/canvas-crowd'
    | '/arena/design-arena'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/arena/activity-heatmap'
    | '/arena/canvas-crowd'
    | '/arena/design-arena'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/arena/activity-heatmap'
    | '/arena/canvas-crowd'
    | '/arena/design-arena'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ArenaActivityHeatmapRoute: typeof ArenaActivityHeatmapRoute
  ArenaCanvasCrowdRoute: typeof ArenaCanvasCrowdRoute
  ArenaDesignArenaRoute: typeof ArenaDesignArenaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arena/activity-heatmap': {
      id: '/arena/activity-heatmap'
      path: '/arena/activity-heatmap'
      fullPath: '/arena/activity-heatmap'
      preLoaderRoute: typeof ArenaActivityHeatmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arena/canvas-crowd': {
      id: '/arena/canvas-crowd'
      path: '/arena/canvas-crowd'
      fullPath: '/arena/canvas-crowd'
      preLoaderRoute: typeof ArenaCanvasCrowdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arena/design-arena': {
      id: '/arena/design-arena'
      path: '/arena/design-arena'
      fullPath: '/arena/design-arena'
      preLoaderRoute: typeof ArenaDesignArenaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ArenaActivityHeatmapRoute: ArenaActivityHeatmapRoute,
  ArenaCanvasCrowdRoute: ArenaCanvasCrowdRoute,
  ArenaDesignArenaRoute: ArenaDesignArenaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
